sonar.projectKey=Real-Estate-App
sonar.projectName=Real Estate App
sonar.projectVersion=1.0

sonar-cloud-token = 49550b0fde29f5fd12329566ff8421a9a14c5d7d

# Set the source encoding and Kotlin language
sonar.sourceEncoding=UTF-8
sonar.language=kotlin

# Specify the paths to source and test files
sonar.sources=src/main/kotlin
sonar.tests=src/test/kotlin

# For Gradle projects, specify binary output directory
sonar.java.binaries=build/classes
