stages:
  - build

before_script:
  - chmod +x ./gradlew  # Ensure Gradle wrapper is executable

build-apk:
  stage: build
  script:
    - ./gradlew assembleRelease
  artifacts:
    paths:
      - app/build/outputs/apk/release/
