org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -XX:+UseG1GC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true
kotlin.parallel.tasks.in.project=true
ksp.incremental=true
ksp.cache.enabled=true

android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableJetifier=false

android.disallowKotlinSourceSets=false

MAPS_API_KEY=your_key_here