package com.application.real_estate_app.core_network.db_names

object FirestoreFields {
        const val ACTIVE = "active"
        const val ADDRESS = "address"
        const val AMENITIES = "amenities"
        const val AREA_SIZE = "areaSize"
        const val AVAILABLE = "available"
        const val AVAILABLE_FROM = "availableFrom"
        const val BATHROOMS = "bathrooms"
        const val BEDROOMS = "bedrooms"
        const val CONTACT_EMAIL = "contactEmail"
        const val CONTACT_PHONE = "contactPhone"
        const val COUNTY = "county"
        const val CREATED_AT = "createdAt"
        const val DEPOSIT_AMOUNT = "depositAmount"
        const val DESCRIPTION = "description"
        const val FEATURES = "features"
        const val ID = "id"
        const val IMAGE_URL = "imageUrl"
        const val LATITUDE = "latitude"
        const val LEASE_TERMS = "leaseTerms"
        const val LONGITUDE = "longitude"
        const val OWNER_ID = "ownerId"
        const val OWNER_NAME = "ownerName"
        const val PRICE = "price"
        const val PROPERTY_TYPE = "propertyType"
        const val TITLE = "title"
        const val VIDEO = "video"
        const val VIDEO_URL = "videoUrl"
        const val VIEWS_COUNT = "viewsCount"
        const val COMMENT = "commentText"
        const val TIMESTAMP = "timeStamp"
        const val USER_ID = "userId"
        const val LIKED_AT = "likedAt"
        const val USER_NAME = "name"
}