object Plugins {
    const val androidApplication = "com.android.application"
    const val androidLibrary = "com.android.library"
    const val kotlinAndroid = "org.jetbrains.kotlin.android"
    const val googleServices = "com.google.gms.google-services"
    const val firebaseCrashlytics = "com.google.firebase.crashlytics"
    const val secretsPlugin = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin"
    const val navigationSafeArgs = "androidx.navigation.safeargs.kotlin"
    const val kapt = "org.jetbrains.kotlin.kapt"
    const val rootKapt = "kapt"
    const val rootAndroid = "android"
    const val rootJvm = "jvm"
    const val hilt = "com.google.dagger.hilt.android"
    const val dokka = "org.jetbrains.dokka"
    const val sonarQube = "org.sonarqube"
    const val room = "androidx.room"
    const val kotlinJvm = "org.jetbrains.kotlin.jvm"
    const val safeArgs = "androidx.navigation.safeargs.kotlin"
}
