name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set executable permission for gradlew
      - name: Set executable permission for gradlew
        run: chmod +x ./gradlew

      # Step 3: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Step 4: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      # Step 5: Generate local.properties
      - name: Generate local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      # Step 6: Build the project
      - name: Build with Gradle
        run: ./gradlew build

      # Step 7: Run Unit Tests
      - name: Run Unit Tests
        run: ./gradlew test
